version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: laravel-app
    ports:
      - 8007:9000
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mongo:4.2.23
    container_name: laravel-mongodb
    ports:
      - 27017:27017
    volumes:
      - database:/var/lib/mongodb/data
    restart: always
    
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8008:80
      - 8443:443
    restart: on-failure
  
volumes:
  database:
